kind: pipeline
type: galaxy
name: build_and_push
platform:
  os: linux
  arch: arm64
steps:
- name: build
  plugin_registry:
    - repo-docker-hosted.angeloxx.lan/angeloxx/drone
  image: plugins/galaxy
  settings:
    key: GITHUB_TOKEN
  when:
    branch:
    - master
    - development
  trigger:
  event:
  - push
  - custom
  branch:
  - master
  - development
