namespace: rangeid
name: bitbucketserver
version: 0.0.2
readme: README.md

authors:
    - Angelo Conforti <a.conforti@range-id.ti>

description: Manage Bitbucket Repository
license:
    - BSD-3-Clause

repository: "https://github.com/rangeid/ansible-bitbucket-collection"
issues: "https://github.com/rangeid/ansible-bitbucket-collection/issues"